name: Build for Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up C Compiler
      run: sudo apt-get install -y gcc make

    - name: Build
      run: |
       make  # or your specific build commands

