name: Codiga Check

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  codacy-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
